spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vibe
    username: vibe
    password: vibe
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

bernmobil:
  mappingrepository:
    datasource:
      url: jdbc:postgresql://localhost:5432/mappings
      username: vibe
      password: vibe
